services:
  hems-api:
    build: .
    restart: unless-stopped
    stop_grace_period: 35s
    init: true
    ports:
      - "127.0.0.1:5000:5000"
    env_file:
      - .env
    shm_size: '256mb'
    security_opt:
      - seccomp:unconfined
